Fix floor_divide
kulinseth/pytorch pull request #243
Opened 2023-01-20 01:39 UTC by Ronian526

- report error for int64
- for int16,int32 cast tensor to float, divide than floor
- unblock floor_divide and divfloor_rounding from testing

2023-01-21 00:49 UTC, razarmehr commented
Can you please add a test case in test_mps for `test_floor_divide()` that could reproduce the issue that you fixed?
Usually, after fixing issues we do that. e.g., if you see `test_pad()`, we have added test cases for each problem we fixed in padding. 
If you add one for floor_divide() it'll make it easy to track what specific problems we fixed (what dimension or data types).

2023-01-23 22:10 UTC, Ronian526 commented on test/test_mps.py
> +    # # Failures due to precision issues, enable after resolving from mps
a = torch.tensor([-616], device="mps",dtype=torch.int32)
b = torch.tensor([28], device="mps",dtype=torch.int32)
z = a.floor_divide(b)
is showing -23, after install mps with fast math off, it shows the proper result (-22)

2023-01-23 23:04 UTC, Ronian526 commented
> 

Sure, thanks Ramin, new test added.

2023-01-25 01:31 UTC, razarmehr approved these changes
LGTM. Please wait for Denis's change for CI runners to merge before merging. Thanks.

2023-01-25 04:22 UTC, DenisVieriu97 commented
@Ronian526 could you please take a look at lint before merging?

2023-01-25 05:07 UTC, DenisVieriu97 approved these changes

2023-01-25 05:09 UTC, DenisVieriu97 requested changes
Looks good - Please take a look at lint before merging

2023-01-27 02:20 UTC, DenisVieriu97 commented on test/test_mps.py
> +                if (rounding_mode != None and "floor" in rounding_mode and dtype == torch.int64) is None:
I think you'll have to do something like this to pass for lint:
```suggestion
                if (rounding_mode is not None and "floor" in rounding_mode and dtype == torch.int64) is None:
```

2023-01-27 17:47 UTC, merged