Enable test nn on MPS and CI runners
kulinseth/pytorch pull request #345
Opened 2023-02-17 22:42 UTC by Ronian526

- test_nn.py hard crash failures: 
  test_conv_empty_input_mps_float16
  test_variable_sequence
  test_elu_inplace_overlap test_gumbel_softmax

2023-02-17 23:03 UTC, DenisVieriu97 commented on test/test_nn.py
> +    @skipIfMps
Can you please add a comment with the reason it's crashing? 
I think if you could do something like `skipMPSIf("Reason")` that would be good (see skipCudaIf). Also I think there are bunch of skipIfMPS in this file that are not needed
By default the floating point dtype in this file is set to double. I think this change got overridden by the recent rebase, but we'd need it to be float for mps (see https://github.com/kulinseth/pytorch/pull/294/files#diff-7927db349f568afca2de9b94d74ea5c3b8cb468cb6a433d0cc1e61e65c515a36R21)

2023-02-17 23:04 UTC, DenisVieriu97 requested changes

2023-02-17 23:04 UTC, DenisVieriu97 commented on test/test_nn.py
> +    @skipIfMps
I think we also need to get rid of all the skipIfMPS that are currently in and check how it goes with `float` dtype

2023-03-08 08:05 UTC, kulinseth commented
@skotapati , can you please take over this PR? I would like to get this one merged.

2023-06-21 19:49 UTC, closed without merging